### PR TITLE
Remove node modules

### PR DESCRIPTION
**Pull request by g1eny0ung**
The `node_modules` should be ignored (but this PR cannot completely remove them from the git repo, the correct approach should be to remove them from the history and force a new history to be pushed. E.g. https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository).

### CODE REVIEW

**Comment by Electroid** [comment]
Hi there, thanks for submitting an issue.

To publish a GitHub action that uses Node.js, you need to publish the `node_modules` directory for it to use npm packages. Here's an [example](https://github.com/denoland/setup-deno/tree/main/node_modules) from another "setup-x" repository.

**Comment by g1eny0ung** [comment]
Thanks, @Electroid. 🤔 But the `setup-deno` doesn't look like a good example, in the usual way we need to package the sources and all their direct dependencies into a production file. But it's ok to commit the `node_modules`, it just has a lot of unnecessary development dependencies... That's what I think is bad about this approach.

Below is an example from docs:

https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

image

**Comment by Electroid** [comment]
@g1eny0ung That makes sense. I think bundling the code would make sense, which Bun will [soon](https://github.com/oven-sh/bun/pull/2312) support! Once that is merged, we can change `setup-bun` to use the bundler, which will output 1 JavaScript file with all the code and `node_modules` bundled together.

**Comment by g1eny0ung** [comment]
> @g1eny0ung That makes sense. I think bundling the code would make sense, which Bun will [soon](https://github.com/oven-sh/bun/pull/2312) support! Once that is merged, we can change `setup-bun` to use the bundler, which will output 1 JavaScript file with all the code and `node_modules` bundled together.

Great!

**Comment by xhyrom** [comment]
> @g1eny0ung That makes sense. I think bundling the code would make sense, which Bun will [soon](https://github.com/oven-sh/bun/pull/2312) support! Once that is merged, we can change `setup-bun` to use the bundler, which will output 1 JavaScript file with all the code and `node_modules` bundled together.

Yep, that make sense 👍

**Comment by xhyrom** [comment]
i did https://github.com/oven-sh/setup-bun/pull/11 because current approach is really bad

**Pull request closed without merging**
