### PR TITLE
fix: use hash instead of url for primary cache key

### LINKED ISSUE #101: cache is not working in gitea/forgejo
because of URL in cache key

before patch: 
image

after patch:
image

patch:
```diff
--- a/src/action.ts
+++ b/src/action.ts
@@ -73,7 +73,7 @@ export default async (options: Input): Promise<Output> => {
   let revision: string | undefined;
   let cacheHit = false;
   if (cacheEnabled) {
-    const cacheRestored = await restoreCache([bunPath], url);
+    const cacheRestored = await restoreCache([bunPath], 'bun-exe');
     if (cacheRestored) {
       revision = await getRevision(bunPath);
       if (revision) {
       
--- a/src/cache-save.ts
+++ b/src/cache-save.ts
@@ -6,7 +6,7 @@ import { CacheState } from "./action";
   const state: CacheState = JSON.parse(getState("cache"));
   if (state.cacheEnabled && !state.cacheHit) {
     try {
-      await saveCache([state.bunPath], state.url);
+      await saveCache([state.bunPath], 'bun-exe');
       process.exit(0);
     } catch (error) {
       warning("Failed to save Bun to cache.");
```

### PR DESCRIPTION
**Pull request by zoto-ff**
its not working when cache key is URL (because of url unsafe characters or smth i think), so i suggest to hash download url and use it as cache key

fixes #101

### CODE REVIEW

**Review by xhyrom — CHANGES_REQUESTED** [review]
follow autofix

**Comment by ghost** [comment]
@xhyrom ?

**Review by xhyrom — APPROVED** [review]
LGTM; I forgot sorry 😅

**Comment by ghost** [comment]
i cant allow edits from maintainers because its cross-org fork (https://github.com/orgs/community/discussions/5634)
but i ran `format` and `build` scripts, so there cant be a problem here?

**Comment by xhyrom** [comment]
I'll move it to the dev branch and then create PR from dev -> main. Thanks!

**Pull request merged**
