### PR TITLE
Make various changes and clean up scripts

### PR DESCRIPTION
**Pull request by Electroid**

### CODE REVIEW

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

**Comment by jord1e** [comment]
@Electroid you broke #27 

https://github.com/oven-sh/setup-bun/commit/a93230df19f891c96f4435f99be379c837116966#diff-0ab5f4d9b6ac7c64ba34246032bebb7d567daffdc4724e50769bd38c6d9c4c66L28

https://github.com/oven-sh/setup-bun/commit/a93230df19f891c96f4435f99be379c837116966#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R34

It should be (in `src/index.ts`)
```diff 
- version: getInput("bun-version") || readVersionFromPackageJson() || undefined,
+ version: readVersionFromPackageJson() || getInput("bun-version") || undefined,
```
because `getInput("bun-version")` always returns the default value (which is `latest`), so the `readVersionFromPackageJson()` is never called.

Would be great if we can get a 1.1.1 out quickly (@xHyroM ).

Also,
```diff
-     if (!packageManager?.startsWith("bun@")) {
+    if (!packageManager?.includes("bun@")) {
```

Yarn does some weird stuff when doing `yarn run` which might still be necessary in setups where only `bun install` is used:
image

Real `package.json`:
image

replacing `startsWith` with `includes` will fix this

**Comment by xhyrom** [comment]
> @Electroid you broke #27 
> 
> https://github.com/oven-sh/setup-bun/commit/a93230df19f891c96f4435f99be379c837116966#diff-0ab5f4d9b6ac7c64ba34246032bebb7d567daffdc4724e50769bd38c6d9c4c66L28
> 
> https://github.com/oven-sh/setup-bun/commit/a93230df19f891c96f4435f99be379c837116966#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R34
> 
> It should be (in `src/index.ts`)
> ```diff 
> - version: getInput("bun-version") || readVersionFromPackageJson() || undefined,
> + version: readVersionFromPackageJson() || getInput("bun-version") || undefined,
> ```
> because `getInput("bun-version")` always returns the default value (which is `latest`), so the `readVersionFromPackageJson()` is never called.
> 
> Would be great if we can get a 1.1.1 out quickly (@xHyroM ).

I didn't catch that, thanks! Well I can publish it tomorrow (UTC+1) because I'm not on computer so I can't build the code.

**Comment by jord1e** [comment]
> > @Electroid you broke #27
> > [a93230d#diff-0ab5f4d9b6ac7c64ba34246032bebb7d567daffdc4724e50769bd38c6d9c4c66L28](https://github.com/oven-sh/setup-bun/commit/a93230df19f891c96f4435f99be379c837116966#diff-0ab5f4d9b6ac7c64ba34246032bebb7d567daffdc4724e50769bd38c6d9c4c66L28)
> > [a93230d#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R34](https://github.com/oven-sh/setup-bun/commit/a93230df19f891c96f4435f99be379c837116966#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R34)
> > It should be (in `src/index.ts`)
> > ```diff
> > - version: getInput("bun-version") || readVersionFromPackageJson() || undefined,
> > + version: readVersionFromPackageJson() || getInput("bun-version") || undefined,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because `getInput("bun-version")` always returns the default value (which is `latest`), so the `readVersionFromPackageJson()` is never called.
> > Would be great if we can get a 1.1.1 out quickly (@xHyroM ).
> 
> I didn't catch that, thanks! Well I can publish it tomorrow (UTC+1) because I'm not on computer so I can't build the code.

I did not expect the quick reply, please see the edit to fix another bug/inconvenience in one go :)

**Comment by xhyrom** [comment]
> > > @Electroid you broke #27
> > > [a93230d#diff-0ab5f4d9b6ac7c64ba34246032bebb7d567daffdc4724e50769bd38c6d9c4c66L28](https://github.com/oven-sh/setup-bun/commit/a93230df19f891c96f4435f99be379c837116966#diff-0ab5f4d9b6ac7c64ba34246032bebb7d567daffdc4724e50769bd38c6d9c4c66L28)
> > > [a93230d#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R34](https://github.com/oven-sh/setup-bun/commit/a93230df19f891c96f4435f99be379c837116966#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R34)
> > > It should be (in `src/index.ts`)
> > > ```diff
> > > - version: getInput("bun-version") || readVersionFromPackageJson() || undefined,
> > > + version: readVersionFromPackageJson() || getInput("bun-version") || undefined,
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > because `getInput("bun-version")` always returns the default value (which is `latest`), so the `readVersionFromPackageJson()` is never called.
> > > Would be great if we can get a 1.1.1 out quickly (@xHyroM ).
> > 
> > I didn't catch that, thanks! Well I can publish it tomorrow (UTC+1) because I'm not on computer so I can't build the code.
> 
> I did not expect the quick reply, please see the edit to fix another bug/inconvenience in one go :)

GitHub actions built it, so I'll release it in few minutes

**Pull request merged**
